name: CI

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: false
          gleam-version: "1.5"

      - name: Check formatting
        run: gleam format --check src test

      - name: Type check
        run: gleam check

      - name: Run tests
        run: gleam test
